# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_body',
            field=models.TextField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
